name: canteen_app
description: "School Canteen App for managing orders, menus, and payments."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Web Plugins (for web-specific features)
  flutter_web_plugins:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.2
  cloud_functions: 5.6.2
  firebase_storage: ^12.3.8
  google_sign_in: ^6.2.1
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Navigation
  go_router: ^14.6.2
  
  # UI Components
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  flutter_svg: ^2.0.16
  
  # Data & Utilities
  intl: ^0.20.1
  uuid: ^4.5.1
  csv: ^6.0.0
  excel: ^4.0.6
  flutter_dotenv: ^5.2.1
  
  # Charts & Graphs
  fl_chart: ^0.70.1
  
  # Responsive Design
  flutter_screenutil: ^5.9.3
  responsive_builder: ^0.7.1
  
  # Forms & Validation
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.0.0
  
  # Monitoring & Logging
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  logger: ^2.4.0
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.14
  riverpod_lint: ^2.6.2
  mockito: ^5.4.4
  test: ^1.25.8
  fake_cloud_firestore: ^3.0.3

flutter:
  uses-material-design: true
  
  # Add assets folders
  assets:
    - assets/images/
    - assets/icons/
    - .env
